### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_IPTVorg#7]
```
version: '2.1'
services:
  fhdhr_iptvorg:
    image: fhdhr_iptvorg:0.4.6
    container_name: fhdhr_iptvorg
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900 # SSD Cluster Port
      - 5004:5004 # Web & HDHR port
    volumes:
      - /<docker-config-directory>/fhdhr_iptvorg:/app/config
    restart: always
```
